export const TasksActionTypes = {
    SET_TASK_DATA: 'SET_PROJECT_DATA',
    SET_TASKS_DATA:'SET_PROJECTS_DATA',
    SET_TASK_EDITING:'SET_PROJECT_EDITING',
    SET_SELECTED_TASK:'SET_SELECTED_PROJECT',
    REMOVE_SELECTED_TASK:'REMOVE_SELECTED_PROJECT'
  };